services:
  db:
    image: ${DOCKER_PG_IMAGE:-postgres:16}
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    expose: # expose port to app container
      - '5432'
    ports: # expose port to host machine in case we want to use external db gui tools
      - '54322:5432'
    volumes:
      - chemotion_db:/var/lib/postgresql/data/

  app:
    image:  mstarman/chemotion-eln-test:0.0.1
    depends_on:
      - 'db'
    env_file:
      - ./.env
    ports: # expose default rails port to host machine
      - "4000:4000"
    volumes:
      - ./shared/pullin:/shared
      - ./shared/backup:/backup
      - ./shared/restore:/restore
      - ./shared/shell_scripts:/shell_scripts

volumes:
  chemotion_db:
    name: ${VOLUME_NAME_DB:-chemotion_db}